'use strict';

const http=require('node:http');const net=require('node:net');const{spawn}=require('node:child_process');const{join}=require('node:path');const database=require('./src/db');const planner=require('./src/ai-study-planner');const digitalTutor=require('./src/digital-tutor');const{row,rows,run}=database;
const PORT=Number(process.env.PORT||3000),UPSTREAM_PORT=Number(process.env.AI_PRO_UPSTREAM_PORT||(PORT+1));
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
async function readJson(req){let data='';for await(const chunk of req){data+=chunk;if(data.length>256*1024)throw Object.assign(new Error('Слишком большой запрос'),{status:413})}try{return JSON.parse(data||'{}')}catch{throw Object.assign(new Error('Некорректный JSON'),{status:400})}}
async function userFor(req){const token=(req.headers.cookie||'').match(/(?:^|; )session=([^;]+)/)?.[1];if(!token)return null;return row('SELECT u.id,u.name,u.email,u.role,u.xp FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>CURRENT_TIMESTAMP',token)}
async function auth(req,res){const user=await userFor(req);if(!user){json(res,401,{error:'Войдите в аккаунт'});return null}return user}
function validSubject(slug){if(!['biology','chemistry'].includes(slug))throw Object.assign(new Error('Выберите биологию или химию'),{status:400});return slug}
async function subjectId(slug){validSubject(slug);const subject=await row('SELECT id FROM subjects WHERE slug=? AND published=1',slug);if(!subject)throw Object.assign(new Error('Предмет не найден'),{status:404});return Number(subject.id)}
async function saveSession(userId,ids,mode='adaptive'){const created=await run('INSERT INTO training_sessions(user_id,topic_id,mode,target_questions) VALUES(?,?,?,?)',userId,null,mode,ids.length);const sessionId=Number(created.lastInsertRowid);for(const[position,questionId]of ids.entries())await run('INSERT INTO training_session_questions(session_id,question_id,position,state) VALUES(?,?,?,?)',sessionId,questionId,position,'pending');return row('SELECT * FROM training_sessions WHERE id=?',sessionId)}
const isoDay=(v=new Date())=>{const d=v instanceof Date?v:new Date(v);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):''};
async function currentPlan(userId,subjectSlug){let plan=await planner.loadPlan(database,userId,subjectSlug);if(!plan)return null;const examTime=Date.parse(`${plan.examDate}T12:00:00`);if(!Number.isFinite(examTime)||examTime<=Date.now())return{...plan,expired:true};const analytics=await planner.collectAnalytics(database,userId,subjectSlug);const needsRefresh=Number(plan.version||0)<Number(planner.PLAN_VERSION||2)||Number(plan.attempts||0)!==Number(analytics.attempts||0)||isoDay(plan.generatedAt)!==isoDay();if(needsRefresh)plan=await planner.buildPlan(database,userId,{subjectSlug,targetScore:plan.targetScore,examDate:plan.examDate,daysPerWeek:plan.daysPerWeek,minutesPerDay:plan.minutesPerDay},{useAi:false,previousPlan:plan,analytics});return plan}
function geminiText(data){return(data?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>typeof p?.text==='string'?p.text:'').filter(Boolean).join('\n').trim()}
async function coachReply(userId,subjectSlug,message,history=[]){
 const plan=await currentPlan(userId,subjectSlug);if(!plan)throw Object.assign(new Error('Сначала заполни анкету и создай план'),{status:409});
 const tutor=await digitalTutor.buildTutorDay(database,userId,subjectSlug,plan);
 const q=String(message||'').trim().slice(0,1500);if(!q)throw Object.assign(new Error('Напиши вопрос'),{status:400});
 if(!process.env.GEMINI_API_KEY)throw Object.assign(new Error('AI-консультант временно недоступен'),{status:503});
 const safeHistory=(Array.isArray(history)?history:[]).slice(-8).map(x=>`${x.role==='assistant'?'Куратор':'Ученик'}: ${String(x.text||'').slice(0,700)}`).join('\n');
 const context={subject:subjectSlug,targetScore:plan.targetScore,examDate:plan.examDate,daysPerWeek:plan.daysPerWeek,minutesPerDay:plan.minutesPerDay,readiness:plan.readiness,coverage:plan.coverage,scoreRange:plan.scoreRange,priorityLines:plan.priorityLines,today:tutor?{title:tutor.title,totalMinutes:tutor.totalMinutes,steps:tutor.steps?.map(s=>({title:s.title,minutes:s.minutes,status:s.status,line:s.line||null}))}:null};
 const prompt=`Ты — цифровой куратор ОСНОВА по подготовке к ЕГЭ. Отвечай ТОЛЬКО про персональный план подготовки к ЕГЭ: что учить, в каком порядке, сколько времени, когда повторять, как скорректировать нагрузку, как работать с ошибками и как выполнить текущий план. Если вопрос не относится к подготовке и плану ЕГЭ, коротко скажи, что здесь обсуждается только план подготовки, и предложи вопрос по плану. Не выдумывай статистику и официальный будущий балл. Используй реальные данные ученика ниже. Отвечай по-русски, конкретно, коротко, без мотивационной воды.\nДанные: ${JSON.stringify(context)}\n${safeHistory?`Последний диалог:\n${safeHistory}\n`:''}Ученик: ${q}`;
 const models=[process.env.GEMINI_PLANNER_MODEL,'gemini-3.8-flash',process.env.GEMINI_MODEL,'gemini-3.7-flash'].filter(Boolean);let last;
 for(const model of [...new Set(models)])try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:700}}),signal:AbortSignal.timeout(15000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Gemini ${r.status}`);const text=geminiText(d);if(text)return{text,subjectSlug}}catch(e){last=e}
 console.warn('ai-pro-coach',last?.message||'no response');throw Object.assign(new Error('Не удалось получить ответ куратора'),{status:503});
}
async function reviewCandidates(userId,subjectSlug,limit=100){const sid=await subjectId(subjectSlug);return rows(`WITH latest AS (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY a.question_id ORDER BY a.id DESC) rn FROM attempts a WHERE a.user_id=?) SELECT q.id,q.exam_line,l.correct,l.next_review_at,l.review_stage,l.created_at FROM latest l JOIN questions q ON q.id=l.question_id WHERE l.rn=1 AND q.subject_id=? AND q.active=1 AND q.published=1 AND (l.correct=0 OR l.next_review_at<=CURRENT_TIMESTAMP) ORDER BY CASE WHEN l.correct=0 THEN 0 ELSE 1 END,COALESCE(l.review_stage,0),l.next_review_at ASC,l.created_at ASC LIMIT ?`,userId,sid,limit)}
async function handleApi(req,res,url){const path=url.pathname;if(!path.startsWith('/api/ai-pro/'))return false;const user=await auth(req,res);if(!user)return true;
 if(path==='/api/ai-pro/plan'&&req.method==='GET'){const subjectSlug=validSubject(String(url.searchParams.get('subject')||'biology'));json(res,200,{plan:await currentPlan(user.id,subjectSlug),openBeta:true,paidFeature:true});return true}
 if(path==='/api/ai-pro/plan'&&req.method==='POST'){const body=await readJson(req),previousPlan=body?.subjectSlug?await planner.loadPlan(database,user.id,String(body.subjectSlug)):null;json(res,200,{plan:await planner.buildPlan(database,user.id,body,{useAi:true,previousPlan}),openBeta:true,paidFeature:true});return true}
 if(path==='/api/ai-pro/tutor/today'&&req.method==='GET'){const subjectSlug=validSubject(String(url.searchParams.get('subject')||'biology')),plan=await currentPlan(user.id,subjectSlug),tutor=await digitalTutor.buildTutorDay(database,user.id,subjectSlug,plan);json(res,200,{tutor,plan});return true}
 if(path==='/api/ai-pro/coach'&&req.method==='POST'){const body=await readJson(req),subjectSlug=validSubject(String(body.subjectSlug||''));json(res,200,await coachReply(user.id,subjectSlug,body.message,body.history));return true}
 if(path==='/api/ai-pro/diagnostic'&&req.method==='POST'){const body=await readJson(req),subjectSlug=validSubject(String(body.subjectSlug||'')),ids=await planner.diagnosticQuestionIds(database,user.id,subjectSlug,Number(body.count)||24);if(ids.length<10)throw Object.assign(new Error('Недостаточно заданий для диагностики'),{status:409});json(res,201,{session:await saveSession(user.id,ids,'adaptive'),questionCount:ids.length,subjectSlug});return true}
 if(path==='/api/ai-pro/review-status'&&req.method==='GET'){const subjectSlug=validSubject(String(url.searchParams.get('subject')||'biology')),list=await reviewCandidates(user.id,subjectSlug,250),wrong=list.filter(i=>!(i.correct===true||i.correct===1||i.correct==='1'||i.correct==='true')).length;json(res,200,{subjectSlug,dueCount:list.length,wrongCount:wrong,ready:list.length>0,recommendedCount:Math.min(12,list.length)});return true}
 if(path==='/api/ai-pro/smart-review'&&req.method==='POST'){const body=await readJson(req),subjectSlug=validSubject(String(body.subjectSlug||'biology')),wanted=Math.max(3,Math.min(30,Number(body.count)||12)),candidates=await reviewCandidates(user.id,subjectSlug,Math.max(80,wanted*6)),ids=[...new Set(candidates.map(i=>Number(i.id)).filter(Boolean))].slice(0,wanted);if(!ids.length)throw Object.assign(new Error('Повторений на сегодня нет'),{status:404});json(res,201,{session:await saveSession(user.id,ids,'review'),questionCount:ids.length,subjectSlug});return true}
 json(res,404,{error:'AI PRO endpoint не найден'});return true}
function proxy(req,res){const headers={...req.headers,host:`127.0.0.1:${UPSTREAM_PORT}`},upstream=http.request({hostname:'127.0.0.1',port:UPSTREAM_PORT,path:req.url,method:req.method,headers},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res)});upstream.on('error',e=>{if(!res.headersSent)json(res,503,{error:'Сервис временно запускается'});else res.end();console.warn('ai-pro-upstream-error',e?.code||'UNKNOWN')});req.pipe(upstream)}
function waitForUpstream(left=180){return new Promise((resolve,reject)=>{const test=n=>{const socket=net.createConnection({host:'127.0.0.1',port:UPSTREAM_PORT});socket.once('connect',()=>{socket.destroy();resolve()});socket.once('error',()=>{socket.destroy();if(n<=0)reject(new Error('AI PRO upstream did not start'));else setTimeout(()=>test(n-1),100)})};test(left)})}
async function start(){const child=spawn(process.execPath,[join(__dirname,'server-training-router.js')],{cwd:__dirname,env:{...process.env,PORT:String(UPSTREAM_PORT),TRAINING_UPSTREAM_PORT:String(UPSTREAM_PORT+1)},stdio:'inherit'});child.on('exit',code=>{if(code)console.error('ai-pro upstream exit',code)});await waitForUpstream();const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{if(await handleApi(req,res,url))return;proxy(req,res)}catch(error){console.error('ai-pro-api',error);if(!res.headersSent)json(res,error?.status||500,{error:error?.status?error.message:'Не удалось выполнить AI PRO запрос'})}});server.listen(PORT,()=>console.log(`EGE platform + AI PRO: http://localhost:${PORT}`));const stop=()=>{child.kill('SIGTERM');server.close(()=>process.exit(0))};process.on('SIGTERM',stop);process.on('SIGINT',stop)}
start().catch(error=>{console.error(error);process.exit(1)});
