const http = require('node:http');
const { readFileSync, existsSync } = require('node:fs');
const { extname, join, normalize } = require('node:path');
const { randomBytes, scryptSync, timingSafeEqual } = require('node:crypto');
const database = require('./src/db');
const { coverageReport } = require('./src/coverage');
const { formatAnswerForReview } = require('./src/answer-review');
const { isCorrectAnswer,needsManualReview } = require('./src/question-answer');
const { search: searchBiology } = require('./src/biology-search');
const { createMockExamService } = require('./src/mock-exams');
const biologyExamRegistry = require('./content/biology/exam-lines.json');
const { migrate, rows, row, run, healthcheck } = database;
const mockExams=createMockExamService(database,biologyExamRegistry);

const portArgument=process.argv.indexOf('--port');
const PORT=Number(process.env.PORT||(portArgument>=0?process.argv[portArgument+1]:3000)), PUBLIC=join(__dirname,'public');
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
class HttpError extends Error { constructor(status,code,message){super(message);this.status=status;this.code=code} }
const body=async req=>{let data='';for await(const chunk of req){data+=chunk;if(data.length>1e6)throw new HttpError(413,'PAYLOAD_TOO_LARGE','Слишком большой запрос');}try{return JSON.parse(data||'{}')}catch{throw new HttpError(400,'INVALID_JSON','Некорректный JSON')}};
const numericId=value=>{const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null};
const biologyGroups=[
 {slug:'science',title:'Биология как наука и методы',description:'Научный метод, уровни организации живого и работа с биологическими данными.',icon:'microscope',sections:['biology-science']},
 {slug:'cell',title:'Молекулярная биология и клетка',description:'Клетка, обмен веществ, ДНК, биосинтез белка и клеточный цикл.',icon:'dna',sections:['biology-molecular','biology-cell']},
 {slug:'organism',title:'Организм, размножение и генетика',description:'Онтогенез, наследственность, изменчивость, селекция и биотехнологии.',icon:'chromosome',sections:['biology-reproduction','biology-genetics']},
 {slug:'diversity',title:'Многообразие организмов',description:'Вирусы, бактерии, грибы, растения и животные — строение и жизненные циклы.',icon:'leaf',sections:['biology-diversity']},
 {slug:'human',title:'Человек и его здоровье',description:'Органы и системы человека, нейрогуморальная регуляция и здоровье.',icon:'human',sections:['biology-human']},
 {slug:'evolution',title:'Эволюция и антропогенез',description:'Механизмы эволюции, происхождение видов и развитие человека.',icon:'tree',sections:['biology-evolution']},
 {slug:'ecology',title:'Экология и биосфера',description:'Экосистемы, пищевые связи, круговороты веществ и устойчивость биосферы.',icon:'ecosystem',sections:['biology-ecology']}
];
async function biologyNavigation(userId){
 const subject=await row("SELECT * FROM subjects WHERE slug='biology' AND published=1");
 const sections=await rows("SELECT id,slug FROM sections WHERE subject_id=? AND published=1",subject.id),bySlug=new Map(sections.map(x=>[x.slug,x.id]));
 const groups=[];
 for(const group of biologyGroups){const ids=group.sections.map(x=>bySlug.get(x)).filter(Boolean);if(!ids.length)continue;const marks=ids.map(()=>'?').join(',');
  const summary=await row(`WITH RECURSIVE tree(id) AS (SELECT id FROM topics WHERE section_id IN (${marks}) AND parent_id IS NULL AND published=1 UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id WHERE t.published=1) SELECT (SELECT COUNT(*) FROM tree JOIN topics t ON t.id=tree.id WHERE t.parent_id IS NULL) child_count,(SELECT COUNT(*) FROM questions q WHERE q.active=1 AND q.topic_id IN (SELECT id FROM tree)) question_count,COALESCE((SELECT ROUND(AVG(tp.mastery)) FROM topic_progress tp WHERE tp.user_id=? AND tp.topic_id IN (SELECT id FROM tree)),0) progress`,...ids,userId);
  groups.push({...group,sectionIds:ids,childCount:Number(summary.child_count),questionCount:Number(summary.question_count),progress:Number(summary.progress)});
 }
 const continued=await row(`SELECT l.id,l.title,COALESCE(lp.reading_progress,0) progress,t.title topic_title FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id JOIN topics t ON t.id=l.topic_id JOIN subjects s ON s.id=t.subject_id WHERE lp.user_id=? AND s.slug='biology' AND l.published=1 AND COALESCE(lp.reading_progress,0)<100 ORDER BY lp.last_opened_at DESC,lp.last_activity_at DESC LIMIT 1`,userId);
 return {subject,groups,continued};
}
const hash=p=>{const s=randomBytes(16).toString('hex');return `${s}:${scryptSync(p,s,64).toString('hex')}`};
const verify=(p,h)=>{const [s,v]=h.split(':');const a=Buffer.from(v,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)};
async function userFor(req){const token=(req.headers.cookie||'').match(/(?:^|; )session=([^;]+)/)?.[1];if(!token)return null;return await row("SELECT u.id,u.name,u.email,u.role,u.xp FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>CURRENT_TIMESTAMP",token)||null;}
async function auth(req,res,admin=false){const u=await userFor(req);if(!u){json(res,401,{error:'Войдите в аккаунт'});return null}if(admin&&u.role!=='admin'){json(res,403,{error:'Недостаточно прав'});return null}return u;}
const safeUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,xp:u.xp,level:Math.floor(u.xp/500)+1});
async function stats(uid){
 const total=await row('SELECT COUNT(*) n, COALESCE(ROUND(AVG(correct)*100),0) accuracy FROM attempts WHERE user_id=?',uid);
 const activity=await rows("SELECT day,solved FROM activity_days WHERE user_id=? ORDER BY day DESC LIMIT 30",uid);
 let streak=0,d=new Date(); const set=new Set(activity.map(a=>a.day)); while(set.has(d.toISOString().slice(0,10))){streak++;d.setUTCDate(d.getUTCDate()-1)}
 const progress=await rows(`WITH RECURSIVE tree(root,id) AS (SELECT id,id FROM topics WHERE parent_id IS NULL UNION ALL SELECT tree.root,t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT root.id,root.slug,root.title,COALESCE(ROUND(AVG(tp.mastery)),0) mastery,COUNT(DISTINCT q.id) questions FROM topics root JOIN tree ON tree.root=root.id LEFT JOIN topic_progress tp ON tp.topic_id=tree.id AND tp.user_id=? LEFT JOIN questions q ON q.topic_id=tree.id WHERE root.parent_id IS NULL GROUP BY root.id ORDER BY root.position`,uid);
 const recent=await rows(`SELECT a.correct,a.created_at,q.prompt,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 5`,uid);
 return {solved:Number(total.n),accuracy:Number(total.accuracy),streak,activity,progress:progress.map(item=>({...item,mastery:Number(item.mastery),questions:Number(item.questions)})),recent,mastery:Math.round(progress.reduce((s,p)=>s+Number(p.mastery),0)/(progress.length||1))};
}
const trainingModes=new Set(['adaptive','mixed','new','review','mistakes','errors','hard','infinite','topic']);
async function questionPool(userId,topicId,mode,limit,examLine=0){
 const scope=`WITH RECURSIVE tree(id) AS (SELECT CAST(? AS BIGINT) UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id),
 latest AS (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY question_id ORDER BY id DESC) rn FROM attempts a WHERE user_id=?)`;
 const filter=mode==='new'?'a.id IS NULL':mode==='review'?"a.id IS NOT NULL AND a.next_review_at<=CURRENT_TIMESTAMP":['mistakes','errors'].includes(mode)?'a.id IS NOT NULL AND a.correct=0':mode==='hard'?'q.difficulty>=2':'1=1';
 return (await rows(`${scope} SELECT q.id FROM questions q LEFT JOIN latest a ON a.question_id=q.id AND a.rn=1
   WHERE q.active=1 AND (?=0 OR q.topic_id IN (SELECT id FROM tree)) AND (?=0 OR q.exam_line=?) AND ${filter}
   ORDER BY CASE
     WHEN a.id IS NOT NULL AND a.correct=0 THEN 0
     WHEN a.id IS NOT NULL AND a.next_review_at<=CURRENT_TIMESTAMP THEN 1
     WHEN a.id IS NULL THEN 2 ELSE 3 END,
     COALESCE(a.next_review_at,'1970-01-01'),q.difficulty,RANDOM() LIMIT ?`,topicId,userId,topicId,examLine,examLine,limit)).map(x=>x.id);
}
async function biologyExamLinePayload(line,userId){
 const item=biologyExamRegistry.lines.find(x=>x.line===line);if(!item)return null;
 const lessons=await rows(`SELECT l.id,l.slug,l.title,t.title topic_title,s.title section_title,COALESCE(lp.reading_progress,0) progress,COALESCE(lp.status,'not_started') progress_status FROM lessons l JOIN topics t ON t.id=l.topic_id JOIN sections s ON s.id=t.section_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.slug IN (${item.lessonRefs.map(()=>'?').join(',')}) AND l.published=1`,userId,...item.lessonRefs);
 const lessonBySlug=new Map(lessons.map(x=>[x.slug,x]));
 const count=await row(`SELECT COUNT(*) n FROM questions q JOIN subjects s ON s.id=q.subject_id WHERE s.slug='biology' AND q.active=1 AND q.exam_line=?`,line);
 const stat=await row(`SELECT COUNT(*) attempted,COALESCE(SUM(a.correct),0) correct,MAX(a.created_at) last_attempt_at FROM attempts a JOIN questions q ON q.id=a.question_id WHERE a.user_id=? AND q.exam_line=?`,userId,line);
 const wrong=await rows(`WITH latest AS (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY question_id ORDER BY id DESC) rn FROM attempts a WHERE user_id=?) SELECT q.external_key FROM latest a JOIN questions q ON q.id=a.question_id WHERE a.rn=1 AND a.correct=0 AND q.exam_line=? ORDER BY a.created_at DESC`,userId,line);
 const examples=await rows(`SELECT q.id,q.type,q.question_type,q.prompt,q.instruction,q.content_json,q.media_json,q.difficulty,q.points,q.max_score,t.title topic FROM questions q JOIN topics t ON t.id=q.topic_id WHERE q.active=1 AND q.exam_line=? ORDER BY q.difficulty,q.id LIMIT 3`,line);
 const attempted=Number(stat.attempted),correct=Number(stat.correct);
 return {...item,questionCount:Number(count.n),lessons:item.lessonRefs.map(x=>lessonBySlug.get(x)).filter(Boolean),examples:examples.map(publicQuestion),progress:{attempted,correct,accuracy:attempted?Math.round(correct/attempted*100):0,lastAttemptAt:stat.last_attempt_at||null,wrongQuestionRefs:wrong.map(x=>x.external_key)}};
}
async function sessionPayload(sessionId,userId){
 const session=await row('SELECT * FROM training_sessions WHERE id=? AND user_id=?',sessionId,userId);
 if(!session)return null;
 const questions=await rows(`SELECT tsq.position,tsq.state,tsq.attempt_id,q.id,q.type,q.prompt,q.instruction,q.content_json,q.media_json,q.difficulty,q.points,q.estimated_seconds,t.title topic
   FROM training_session_questions tsq JOIN questions q ON q.id=tsq.question_id JOIN topics t ON t.id=q.topic_id
   WHERE tsq.session_id=? ORDER BY tsq.position`,sessionId);
 return {...session,questions};
}
const parseJsonArray=value=>{try{const parsed=typeof value==='string'?JSON.parse(value):value;return Array.isArray(parsed)?parsed:[]}catch{return []}};
const publicQuestion=q=>({id:q.id,type:q.type,questionType:q.question_type||q.type,manualReview:needsManualReview(q),prompt:q.prompt,instruction:q.instruction,contentJson:q.content_json,mediaJson:q.media_json,imageUrl:q.image_url,difficulty:q.difficulty,points:q.points,maxScore:q.max_score,estimatedSeconds:q.estimated_seconds,topic:q.topic});
async function recordAnswer(userId,q,b,db=database,resolutionType='answered'){
 const {row,run}=db;
 const expected=JSON.parse(q.answer_json),given=resolutionType==='revealed'?[]:Array.isArray(b.answer)?b.answer.map(String):[String(b.answer??'')],norm=a=>a.map(x=>x.trim().toLowerCase());
 const manual=resolutionType==='answered'&&needsManualReview(q);
 if(manual&&!['understood','repeat'].includes(b.selfAssessment))throw new HttpError(400,'SELF_REVIEW_REQUIRED','Сначала сверьте ответ с критериями и выберите результат самопроверки');
 if(manual)resolutionType='self_assessed';
 const correct=manual?b.selfAssessment==='understood':resolutionType==='answered'&&isCorrectAnswer(q,given);
 const previous=await row('SELECT review_stage FROM attempts WHERE user_id=? AND question_id=? ORDER BY id DESC LIMIT 1',userId,q.id),stage=correct?Math.min(5,(previous?.review_stage||0)+1):0,interval=[1,2,4,7,14,30][stage];
 const nextReviewAt=new Date(Date.now()+interval*86400000).toISOString();
 const reviewAnswer=formatAnswerForReview(q,await db.rows('SELECT value,label FROM question_options WHERE question_id=? ORDER BY position',q.id));
 const xp=resolutionType==='revealed'?0:manual?(correct?5:0):correct?20:5,result={correct,expected,reviewAnswer,explanation:q.explanation,solutionSteps:parseJsonArray(q.solution_steps_json),maxScore:q.max_score||q.points||1,resolutionType,selfAssessment:manual?b.selfAssessment:null,xp,nextReviewInDays:interval};
 const attempt=await run("INSERT INTO attempts(user_id,question_id,answer_json,correct,duration_seconds,next_review_at,interval_days,review_stage,result_json) VALUES(?,?,?,?,?,?,?,?,?)",userId,q.id,JSON.stringify(given),correct,Math.max(0,Number(b.duration)||0),nextReviewAt,interval,stage,JSON.stringify(result));
 await run("INSERT INTO activity_days(user_id,day,solved) VALUES(?,CURRENT_DATE,1) ON CONFLICT(user_id,day) DO UPDATE SET solved=activity_days.solved+1",userId);await run('UPDATE users SET xp=xp+? WHERE id=?',xp,userId);
 const topicStats=await row('SELECT COUNT(*) n,AVG(correct)*100 score FROM attempts a JOIN questions q ON q.id=a.question_id WHERE a.user_id=? AND q.topic_id=?',userId,q.topic_id),attemptCount=Number(topicStats.n),mastery=Math.min(100,Math.round(Number(topicStats.score)*Math.min(1,attemptCount/5)));
 await run("INSERT INTO topic_progress(user_id,topic_id,mastery) VALUES(?,?,?) ON CONFLICT(user_id,topic_id) DO UPDATE SET mastery=excluded.mastery,updated_at=CURRENT_TIMESTAMP",userId,q.topic_id,mastery);
 if(q.lesson_id) await run(`INSERT INTO lesson_progress(user_id,lesson_id,status,questions_solved,correct_answers,last_activity_at,last_opened_at)
   VALUES(?,?,'in_progress',1,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,lesson_id) DO UPDATE SET
   status=CASE WHEN lesson_progress.status='completed' OR lesson_progress.questions_solved+1>=5 THEN 'completed' ELSE 'in_progress' END,
   questions_solved=lesson_progress.questions_solved+1,correct_answers=lesson_progress.correct_answers+excluded.correct_answers,
   last_activity_at=CURRENT_TIMESTAMP,last_opened_at=CURRENT_TIMESTAMP,completed_at=CASE WHEN lesson_progress.questions_solved+1>=5 THEN CURRENT_TIMESTAMP ELSE lesson_progress.completed_at END`,userId,q.lesson_id,correct?1:0);
 return {...result,attemptId:Number(attempt.lastInsertRowid)};
}
async function savedResolution(item,userId,db=database){
 if(!item?.attempt_id)return null;const attempt=await db.row('SELECT result_json FROM attempts WHERE id=? AND user_id=?',item.attempt_id,userId);if(!attempt)return null;
 const result=JSON.parse(attempt.result_json);return {...result,attemptId:Number(item.attempt_id),alreadySaved:true};
}
async function api(req,res,path){
 try{
  if(path==='/api/health'){await healthcheck();const migration=await row('SELECT COUNT(*) n FROM schema_migrations');return json(res,200,{status:'ok',database:'connected',migrations:Number(migration.n)})}
  if(path==='/api/register'&&req.method==='POST'){const b=await body(req);if(!b.name?.trim()||!/^[^@]+@[^@]+\.[^@]+$/.test(b.email||'')||(b.password||'').length<8)return json(res,400,{error:'Укажите имя, корректную почту и пароль от 8 символов'});try{const x=await run('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)',b.name.trim(),b.email.toLowerCase(),hash(b.password));return await login(res,Number(x.lastInsertRowid));}catch(error){if(error.code==='23505'||error.code==='ERR_SQLITE_CONSTRAINT_UNIQUE')return json(res,409,{error:'Эта почта уже зарегистрирована',code:'EMAIL_EXISTS'});throw error}}
  if(path==='/api/login'&&req.method==='POST'){const b=await body(req),u=await row('SELECT * FROM users WHERE email=?',(b.email||'').toLowerCase());if(!u||!verify(b.password||'',u.password_hash))return json(res,401,{error:'Неверная почта или пароль'});return await login(res,u.id)}
  if(path==='/api/logout'&&req.method==='POST'){const token=(req.headers.cookie||'').match(/session=([^;]+)/)?.[1];if(token)await run('DELETE FROM sessions WHERE token=?',token);res.setHeader('set-cookie','session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax');return json(res,200,{ok:true})}
  if(path==='/api/me'){const u=await auth(req,res);if(u)return json(res,200,{user:safeUser(u),stats:await stats(u.id),examDate:process.env.EXAM_DATE||'2027-06-05'})}
  if(path==='/api/leaderboard'&&req.method==='GET'){
    res.setHeader('cache-control','no-store');
    const u=await auth(req,res);if(!u)return;
    const leaders=await rows("SELECT id,name,xp FROM users WHERE role='student' ORDER BY xp DESC,id ASC LIMIT 5");
    return json(res,200,{leaders:leaders.map((leader,index)=>({rank:index+1,name:leader.name,xp:Number(leader.xp)||0,isYou:String(leader.id)===String(u.id)}))});
  }
  if(path==='/api/subjects'){const u=await auth(req,res);if(u)return json(res,200,{subjects:await rows('SELECT * FROM subjects WHERE published=1 ORDER BY position,id')})}
  if(path==='/api/subjects/biology/search'&&req.method==='GET'){
    const u=await auth(req,res);if(!u)return;
    const query=new URL(req.url,'http://x').searchParams.get('q')||'';
    if(query.trim().length<2||query.length>240)return json(res,400,{error:'Введите от 2 до 240 символов'});
    const lessons=await rows("SELECT l.id,l.slug FROM lessons l JOIN topics t ON t.id=l.topic_id JOIN subjects s ON s.id=t.subject_id WHERE s.slug='biology' AND l.published=1 AND t.published=1");
    const ids=new Map(lessons.map(l=>[l.slug,Number(l.id)]));
    return json(res,200,{hits:searchBiology(query).filter(hit=>ids.has(hit.lessonSlug)).map(hit=>({...hit,lessonId:ids.get(hit.lessonSlug)}))});
  }
  if(path==='/api/subjects/biology/navigation'){const u=await auth(req,res);if(u)return json(res,200,await biologyNavigation(u.id))}
  if(path==='/api/subjects/biology/exam-lines'){const u=await auth(req,res);if(!u)return;const lines=[];for(const item of biologyExamRegistry.lines){const payload=await biologyExamLinePayload(item.line,u.id);lines.push({line:item.line,title:item.title,part:item.part,answerFormat:item.answerFormat,shortDescription:item.shortDescription,questionCount:payload.questionCount,progress:payload.progress})}return json(res,200,{examYear:biologyExamRegistry.examYear,sourceStatus:biologyExamRegistry.sourceStatus,lines})}
  if(path.startsWith('/api/subjects/biology/mock-exams')){const u=await auth(req,res);if(!u)return;return mockExams.handle(req,res,path,u,json,body)}
  if(path.match(/^\/api\/subjects\/biology\/exam-lines\/\d+$/)){const u=await auth(req,res);if(!u)return;const line=numericId(path.split('/').pop()),payload=await biologyExamLinePayload(line,u.id);return payload?json(res,200,{line:payload}):json(res,404,{error:'Линия задания не найдена',code:'EXAM_LINE_NOT_FOUND'})}
  if(path.match(/^\/api\/subjects\/biology\/groups\/[a-z0-9-]+$/)){const u=await auth(req,res);if(!u)return;const slug=path.split('/').pop(),navigation=await biologyNavigation(u.id),group=navigation.groups.find(x=>x.slug===slug);if(!group)return json(res,404,{error:'Раздел не найден',code:'GROUP_NOT_FOUND'});const marks=group.sectionIds.map(()=>'?').join(',');const topics=await rows(`WITH RECURSIVE tree(root,id) AS (SELECT id,id FROM topics WHERE section_id IN (${marks}) AND parent_id IS NULL AND published=1 UNION ALL SELECT tree.root,t.id FROM topics t JOIN tree ON t.parent_id=tree.id WHERE t.published=1) SELECT root.*,(SELECT COUNT(*) FROM questions q WHERE q.active=1 AND q.topic_id IN (SELECT id FROM tree x WHERE x.root=root.id)) question_count,COALESCE((SELECT ROUND(AVG(tp.mastery)) FROM topic_progress tp WHERE tp.user_id=? AND tp.topic_id IN (SELECT id FROM tree x WHERE x.root=root.id)),0) progress,(SELECT COUNT(*) FROM topics c WHERE c.parent_id=root.id AND c.published=1) child_count,(SELECT COUNT(*) FROM lessons l WHERE l.topic_id=root.id AND l.published=1) lesson_count FROM topics root WHERE root.id IN (SELECT root FROM tree) ORDER BY root.position,root.id`,...group.sectionIds,u.id);return json(res,200,{subject:navigation.subject,group,topics})}
  if(path.match(/^\/api\/subjects\/[a-z0-9-]+$/)){const u=await auth(req,res);if(!u)return;const slug=path.split('/').pop();const subject=await row('SELECT * FROM subjects WHERE slug=? AND published=1',slug);if(!subject)return json(res,404,{error:'Предмет не найден',code:'SUBJECT_NOT_FOUND'});return json(res,200,{subject,sections:await rows('SELECT * FROM sections WHERE subject_id=? AND published=1 ORDER BY position,id',subject.id)})}
  if(path.match(/^\/api\/sections\/\d+$/)){const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/').pop());if(!id)return json(res,400,{error:'Некорректный идентификатор раздела',code:'INVALID_ID'});const section=await row('SELECT * FROM sections WHERE id=? AND published=1',id);if(!section)return json(res,404,{error:'Раздел не найден',code:'SECTION_NOT_FOUND'});return json(res,200,{section,topics:await rows('SELECT * FROM topics WHERE section_id=? AND parent_id IS NULL AND published=1 ORDER BY position,id',id)})}
  if(path.match(/^\/api\/lessons\/\d+$/)){const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/').pop());if(!id)return json(res,400,{error:'Некорректный идентификатор урока',code:'INVALID_ID'});const lesson=await row('SELECT l.*,t.title topic_title,t.subject_id FROM lessons l JOIN topics t ON t.id=l.topic_id WHERE l.id=? AND l.published=1',id);if(!lesson)return json(res,404,{error:'Урок не найден',code:'LESSON_NOT_FOUND'});const blocks=await rows('SELECT id,type,content_json,position FROM lesson_blocks WHERE lesson_id=? ORDER BY position',id);const breadcrumbs=await rows(`WITH RECURSIVE chain(id,parent_id,title,depth) AS (SELECT id,parent_id,title,0 FROM topics WHERE id=? UNION ALL SELECT t.id,t.parent_id,t.title,chain.depth+1 FROM topics t JOIN chain ON chain.parent_id=t.id) SELECT id,title FROM chain ORDER BY depth DESC`,lesson.topic_id);const nextLesson=await row('SELECT id,title FROM lessons WHERE topic_id=? AND published=1 AND (position>? OR (position=? AND id>?)) ORDER BY position,id LIMIT 1',lesson.topic_id,lesson.position,lesson.position,lesson.id);return json(res,200,{lesson,blocks,breadcrumbs,nextLesson,progress:await row('SELECT * FROM lesson_progress WHERE user_id=? AND lesson_id=?',u.id,id)||{reading_progress:0,status:'not_started'}})}
  if(path==='/api/topics'){const u=await auth(req,res);if(!u)return;return json(res,200,{topics:await rows(`WITH RECURSIVE descendants(root,id) AS (SELECT id,id FROM topics UNION ALL SELECT descendants.root,t.id FROM topics t JOIN descendants ON t.parent_id=descendants.id) SELECT t.*,COALESCE(ROUND(AVG(tp.mastery)),0) mastery,COUNT(DISTINCT q.id) question_count FROM topics t JOIN descendants d ON d.root=t.id LEFT JOIN topic_progress tp ON tp.topic_id=d.id AND tp.user_id=? LEFT JOIN questions q ON q.topic_id=d.id WHERE t.published=1 GROUP BY t.id ORDER BY t.position,t.id`,u.id)})}
  if(path.match(/^\/api\/topics\/\d+$/)){const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/').pop());if(!id)return json(res,400,{error:'Некорректный идентификатор темы'});const topic=await row(`WITH RECURSIVE tree(id) AS (SELECT CAST(? AS BIGINT) UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT t.*,s.title subject,COALESCE((SELECT ROUND(AVG(tp.mastery)) FROM topic_progress tp WHERE tp.user_id=? AND tp.topic_id IN (SELECT id FROM tree)),0) mastery,(SELECT COUNT(*) FROM questions q WHERE q.active=1 AND q.topic_id IN (SELECT id FROM tree)) question_count FROM topics t JOIN subjects s ON s.id=t.subject_id WHERE t.id=? AND t.published=1`,id,u.id,id);if(!topic)return json(res,404,{error:'Тема не найдена'});const stat=await row(`WITH RECURSIVE tree(id) AS (SELECT CAST(? AS BIGINT) UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT COUNT(*) attempted,COALESCE(SUM(correct),0) correct FROM attempts a JOIN questions q ON q.id=a.question_id WHERE a.user_id=? AND q.topic_id IN (SELECT id FROM tree)`,id,u.id);const breadcrumbs=await rows(`WITH RECURSIVE chain(id,parent_id,title,depth) AS (SELECT id,parent_id,title,0 FROM topics WHERE id=? UNION ALL SELECT t.id,t.parent_id,t.title,chain.depth+1 FROM topics t JOIN chain ON chain.parent_id=t.id) SELECT id,title FROM chain ORDER BY depth DESC`,id);const lessons=await rows(`SELECT l.*,COALESCE(lp.reading_progress,0) progress,COALESCE(lp.status,'not_started') progress_status FROM lessons l LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.topic_id=? AND l.published=1 ORDER BY l.position,l.id`,u.id,id);return json(res,200,{topic,breadcrumbs,children:await rows('SELECT * FROM topics WHERE parent_id=? AND published=1 ORDER BY position',id),lessons,continueLesson:lessons.find(l=>l.progress_status!=='completed')||null,stat})}
  if(path==='/api/attempts'){const u=await auth(req,res);if(!u)return;const url=new URL(req.url,'http://x'),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||30));return json(res,200,{attempts:await rows('SELECT a.id,a.answer_json,a.correct,a.duration_seconds,a.created_at,a.next_review_at,a.interval_days,a.review_stage,a.result_json,q.prompt,q.type,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT ?',u.id,limit)})}
  if(path==='/api/skills'){const u=await auth(req,res);if(!u)return;return json(res,200,{skills:await rows(`SELECT s.*,COUNT(DISTINCT qs.question_id) question_count,COALESCE(ROUND(AVG(a.correct)*100),0) accuracy
    FROM skills s LEFT JOIN question_skills qs ON qs.skill_id=s.id LEFT JOIN attempts a ON a.question_id=qs.question_id AND a.user_id=? GROUP BY s.id ORDER BY s.position,s.id`,u.id)})}
  if(path==='/api/lesson-progress'){const u=await auth(req,res);if(!u)return;return json(res,200,{lessons:await rows('SELECT lp.*,l.title,l.slug FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id WHERE lp.user_id=? ORDER BY lp.last_activity_at DESC',u.id)})}
  if(path.match(/^\/api\/lesson-progress\/\d+$/)&&req.method==='POST'){const u=await auth(req,res);if(!u)return;const lessonId=numericId(path.split('/').pop());if(!lessonId)return json(res,400,{error:'Некорректный идентификатор урока',code:'INVALID_ID'});const lesson=await row('SELECT id FROM lessons WHERE id=? AND published=1',lessonId);if(!lesson)return json(res,404,{error:'Урок не найден',code:'LESSON_NOT_FOUND'});const b=await body(req),progress=Number(b.readingProgress??(b.theoryRead?100:0));if(!Number.isFinite(progress)||progress<0||progress>100)return json(res,400,{error:'Прогресс должен быть от 0 до 100',code:'INVALID_PROGRESS'});const value=Math.round(progress),status=value>=90?'completed':'in_progress';await run(`INSERT INTO lesson_progress(user_id,lesson_id,status,theory_read,reading_progress,last_activity_at,last_opened_at,completed_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CASE WHEN ?='completed' THEN CURRENT_TIMESTAMP END)
    ON CONFLICT(user_id,lesson_id) DO UPDATE SET status=CASE WHEN lesson_progress.status='completed' THEN 'completed' ELSE excluded.status END,theory_read=CASE WHEN lesson_progress.theory_read OR excluded.theory_read THEN TRUE ELSE FALSE END,reading_progress=CASE WHEN lesson_progress.reading_progress>excluded.reading_progress THEN lesson_progress.reading_progress ELSE excluded.reading_progress END,last_activity_at=CURRENT_TIMESTAMP,last_opened_at=CURRENT_TIMESTAMP,completed_at=CASE WHEN excluded.status='completed' THEN COALESCE(lesson_progress.completed_at,CURRENT_TIMESTAMP) ELSE lesson_progress.completed_at END`,u.id,lessonId,status,value>=90,value,status);return json(res,200,{progress:await row('SELECT * FROM lesson_progress WHERE user_id=? AND lesson_id=?',u.id,lessonId)})}
  if(path==='/api/training/sessions'&&req.method==='POST'){
   const u=await auth(req,res);if(!u)return;const b=await body(req),mode=trainingModes.has(b.mode)?b.mode:'adaptive',topicId=b.topicId===undefined||b.topicId===null||b.topicId===0?0:numericId(b.topicId),examLine=b.examLine===undefined||b.examLine===null||b.examLine===0?0:numericId(b.examLine),target=Math.min(100,Math.max(1,Number(b.targetQuestions)||10));if(topicId===null)return json(res,400,{error:'Некорректный идентификатор темы'});if(examLine===null||examLine>28||examLine&&!biologyExamRegistry.lines.some(x=>x.line===examLine))return json(res,400,{error:'Некорректный номер задания',code:'INVALID_EXAM_LINE'});
   let ids=await questionPool(u.id,topicId,mode,target,examLine);if(!ids.length&&mode!=='adaptive')ids=await questionPool(u.id,topicId,'adaptive',target,examLine);
   if(!ids.length)return json(res,404,{error:'Для выбранной тренировки пока нет заданий'});
   const storedMode=mode==='errors'?'mistakes':['mixed','hard','infinite'].includes(mode)?'adaptive':mode;
   const created=await run('INSERT INTO training_sessions(user_id,topic_id,mode,target_questions) VALUES(?,?,?,?)',u.id,topicId||null,storedMode,Math.min(target,ids.length)),sessionId=Number(created.lastInsertRowid);
   for (const [position,id] of ids.entries()) await run('INSERT INTO training_session_questions(session_id,question_id,position) VALUES(?,?,?)',sessionId,id,position);
   return json(res,201,{session:await sessionPayload(sessionId,u.id)});
  }
  if(path==='/api/training/sessions/current'){const u=await auth(req,res);if(!u)return;const active=await row("SELECT id FROM training_sessions WHERE user_id=? AND status='active' ORDER BY id DESC LIMIT 1",u.id);return json(res,200,{session:active?await sessionPayload(active.id,u.id):null})}
  if(path.match(/^\/api\/training\/sessions\/\d+$/)&&req.method==='GET'){const u=await auth(req,res);if(!u)return;const session=await sessionPayload(numericId(path.split('/').pop()),u.id);return session?json(res,200,{session}):json(res,404,{error:'Тренировка не найдена'})}
  if(path.match(/^\/api\/training\/sessions\/\d+\/next$/)&&req.method==='GET'){
   const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/')[4]);if(!id)return json(res,400,{error:'Некорректный идентификатор тренировки'});const session=await row("SELECT * FROM training_sessions WHERE id=? AND user_id=? AND status='active'",id,u.id);if(!session)return json(res,404,{error:'Активная тренировка не найдена'});
   const item=await row(`SELECT tsq.position,q.* FROM training_session_questions tsq JOIN questions q ON q.id=tsq.question_id WHERE tsq.session_id=? AND tsq.state='pending' ORDER BY tsq.position LIMIT 1`,id);
   if(!item){await run("UPDATE training_sessions SET status='completed',finished_at=CURRENT_TIMESTAMP WHERE id=?",id);return json(res,200,{done:true,session:await sessionPayload(id,u.id)})}
   await run("UPDATE training_session_questions SET presented_at=COALESCE(presented_at,CURRENT_TIMESTAMP) WHERE session_id=? AND position=?",id,item.position);
   return json(res,200,{session:{id,mode:session.mode,answeredCount:session.answered_count,targetQuestions:session.target_questions},question:publicQuestion(item),options:await rows('SELECT value,label FROM question_options WHERE question_id=? ORDER BY position',item.id)})
  }
  if(path.match(/^\/api\/training\/sessions\/\d+\/review$/)&&req.method==='POST'){
   const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/')[4]),b=await body(req),questionId=numericId(b.questionId);
   if(!id||!questionId)return json(res,400,{error:'Некорректный идентификатор'});
   const q=await row("SELECT q.* FROM training_session_questions tsq JOIN training_sessions s ON s.id=tsq.session_id JOIN questions q ON q.id=tsq.question_id WHERE s.id=? AND s.user_id=? AND s.status='active' AND tsq.state='pending' AND q.id=?",id,u.id,questionId);
   if(!q)return json(res,404,{error:'Активное задание не найдено'});
   if(!needsManualReview(q))return json(res,400,{error:'У задания есть автоматическая проверка'});
   const metadata=typeof q.explanation_json==='string'?JSON.parse(q.explanation_json||'{}'):(q.explanation_json||{});
   return json(res,200,{manualReview:true,reviewAnswer:formatAnswerForReview(q,await rows('SELECT value,label FROM question_options WHERE question_id=? ORDER BY position',q.id)),explanation:q.explanation,solutionSteps:parseJsonArray(q.solution_steps_json),scoringPoints:metadata.scoringPoints||[]});
  }
  if(path.match(/^\/api\/training\/sessions\/\d+\/answer$/)&&req.method==='POST'){
   const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/')[4]),b=await body(req),questionId=numericId(b.questionId);if(!id||!questionId)return json(res,400,{error:'Некорректный идентификатор'});
   const saved=await database.transaction(async tx=>{const item=await tx.row(`SELECT tsq.position,tsq.state,tsq.attempt_id,q.* FROM training_session_questions tsq JOIN training_sessions s ON s.id=tsq.session_id JOIN questions q ON q.id=tsq.question_id WHERE s.id=? AND s.user_id=? AND q.id=?`,id,u.id,questionId);if(!item||item.state!=='pending')throw new HttpError(409,'ATTEMPT_COMPLETED','Задание уже завершено');const claimed=await tx.run("UPDATE training_session_questions SET state='answered',answered_at=CURRENT_TIMESTAMP WHERE session_id=? AND position=? AND state='pending'",id,item.position);if(!claimed.changes)throw new HttpError(409,'ATTEMPT_COMPLETED','Задание уже завершено');const result=await recordAnswer(u.id,item,b,tx);await tx.run('UPDATE training_session_questions SET attempt_id=? WHERE session_id=? AND position=?',result.attemptId,id,item.position);await tx.run('UPDATE training_sessions SET answered_count=answered_count+1,correct_count=correct_count+? WHERE id=?',result.correct?1:0,id);const left=Number((await tx.row("SELECT COUNT(*) n FROM training_session_questions WHERE session_id=? AND state='pending'",id)).n);if(left===0)await tx.run("UPDATE training_sessions SET status='completed',finished_at=CURRENT_TIMESTAMP WHERE id=?",id);return {result,left}});
   return json(res,200,{...saved.result,done:saved.left===0,session:await sessionPayload(id,u.id),stats:await stats(u.id)});
  }
  if(path.match(/^\/api\/training\/sessions\/\d+\/reveal$/)&&req.method==='POST'){
   const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/')[4]),b=await body(req),questionId=numericId(b.questionId);if(!id||!questionId)return json(res,400,{error:'Некорректный идентификатор'});
   const saved=await database.transaction(async tx=>{const item=await tx.row(`SELECT tsq.position,tsq.state,tsq.attempt_id,q.* FROM training_session_questions tsq JOIN training_sessions s ON s.id=tsq.session_id JOIN questions q ON q.id=tsq.question_id WHERE s.id=? AND s.user_id=? AND q.id=?`,id,u.id,questionId);if(!item)throw new HttpError(404,'QUESTION_NOT_FOUND','Задание не входит в тренировку');if(item.state!=='pending'){const previous=await savedResolution(item,u.id,tx);if(previous?.resolutionType==='revealed')return {result:previous,left:Number((await tx.row("SELECT COUNT(*) n FROM training_session_questions WHERE session_id=? AND state='pending'",id)).n)};throw new HttpError(409,'ATTEMPT_COMPLETED','Задание уже завершено');}const claimed=await tx.run("UPDATE training_session_questions SET state='skipped',answered_at=CURRENT_TIMESTAMP WHERE session_id=? AND position=? AND state='pending'",id,item.position);if(!claimed.changes)throw new HttpError(409,'ATTEMPT_COMPLETED','Задание уже завершено');const result=await recordAnswer(u.id,item,b,tx,'revealed');await tx.run('UPDATE training_session_questions SET attempt_id=? WHERE session_id=? AND position=?',result.attemptId,id,item.position);await tx.run('UPDATE training_sessions SET answered_count=answered_count+1 WHERE id=?',id);const left=Number((await tx.row("SELECT COUNT(*) n FROM training_session_questions WHERE session_id=? AND state='pending'",id)).n);if(left===0)await tx.run("UPDATE training_sessions SET status='completed',finished_at=CURRENT_TIMESTAMP WHERE id=?",id);return {result,left}});
   return json(res,200,{...saved.result,done:saved.left===0,session:await sessionPayload(id,u.id),stats:await stats(u.id)});
  }
  if(path.match(/^\/api\/training\/sessions\/\d+\/finish$/)&&req.method==='POST'){const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/')[4]);if(!id)return json(res,400,{error:'Некорректный идентификатор тренировки'});await run("UPDATE training_sessions SET status=CASE WHEN answered_count>=target_questions THEN 'completed' ELSE 'abandoned' END,finished_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND status='active'",id,u.id);const session=await sessionPayload(id,u.id);return session?json(res,200,{session}):json(res,404,{error:'Тренировка не найдена'})}
  if(path.match(/^\/api\/training\/result\/\d+$/)){const u=await auth(req,res);if(!u)return;const id=numericId(path.split('/').pop());if(!id)return json(res,400,{error:'Некорректный идентификатор результата'});const result=await row('SELECT a.id,a.answer_json,a.correct,a.duration_seconds,a.created_at,a.next_review_at,a.interval_days,a.review_stage,a.result_json,q.prompt,q.explanation,q.answer_json expected_json,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.id=? AND a.user_id=?',id,u.id);return result?json(res,200,{result}):json(res,404,{error:'Результат не найден'})}
  if(path==='/api/training/next'){const u=await auth(req,res);if(!u)return;const url=new URL(req.url,'http://x'),rawTopic=url.searchParams.get('topic'),topic=rawTopic===null||rawTopic==='0'?0:numericId(rawTopic);if(topic===null)return json(res,400,{error:'Некорректный идентификатор темы'});let q=await row(`WITH RECURSIVE tree(id) AS (SELECT CAST(? AS BIGINT) UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id), last_attempt AS (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY question_id ORDER BY id DESC) rn FROM attempts a WHERE user_id=?) SELECT q.* FROM questions q LEFT JOIN last_attempt a ON a.question_id=q.id AND a.rn=1 WHERE q.active=1 AND (?=0 OR q.topic_id IN (SELECT id FROM tree)) AND (a.id IS NULL OR a.next_review_at<=CURRENT_TIMESTAMP) ORDER BY CASE WHEN a.id IS NULL THEN 0 ELSE 1 END,a.next_review_at,q.difficulty,RANDOM() LIMIT 1`,topic,u.id,topic);if(!q)q=await row(`WITH RECURSIVE tree(id) AS (SELECT CAST(? AS BIGINT) UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT q.* FROM questions q WHERE q.active=1 AND (?=0 OR q.topic_id IN (SELECT id FROM tree)) ORDER BY RANDOM() LIMIT 1`,topic,topic);if(!q)return json(res,404,{error:'Для этой темы пока нет заданий'});return json(res,200,{question:publicQuestion(q),options:await rows('SELECT value,label FROM question_options WHERE question_id=? ORDER BY position',q.id)})}
  if(path==='/api/training/answer'&&req.method==='POST'){
   const u=await auth(req,res);if(!u)return;const b=await body(req),questionId=numericId(b.questionId);if(!questionId)return json(res,400,{error:'Некорректный идентификатор задания'});const q=await row('SELECT * FROM questions WHERE id=? AND active=1',questionId);if(!q)return json(res,404,{error:'Задание не найдено'});
   const result=await database.transaction(tx=>recordAnswer(u.id,q,b,tx));return json(res,200,{...result,stats:await stats(u.id)});
  }
  if(path==='/api/admin/stats'){const u=await auth(req,res,true);if(u)return json(res,200,{users:await rows(`SELECT u.id,u.name,u.email,u.xp,COUNT(a.id) solved,COALESCE(ROUND(AVG(a.correct)*100),0) accuracy FROM users u LEFT JOIN attempts a ON a.user_id=u.id WHERE u.role='student' GROUP BY u.id ORDER BY solved DESC`),counts:await row("SELECT (SELECT COUNT(*) FROM users WHERE role='student') students,(SELECT COUNT(*) FROM questions) questions,(SELECT COUNT(*) FROM attempts) attempts")})}
  if(path==='/api/admin/coverage'){const u=await auth(req,res,true);if(!u)return;const url=new URL(req.url,'http://x'),year=Number(url.searchParams.get('year'))||2027,subject=url.searchParams.get('subject')||'biology';return json(res,200,{subject,examYear:year,items:await coverageReport(database,subject,year)})}
  if(path==='/api/admin/questions'&&req.method==='GET'){const u=await auth(req,res,true);if(u)return json(res,200,{questions:await rows('SELECT q.id,q.prompt,q.type,q.difficulty,q.active,t.title topic FROM questions q JOIN topics t ON t.id=q.topic_id ORDER BY q.id DESC')})}
  if(path==='/api/admin/questions'&&req.method==='POST'){const u=await auth(req,res,true);if(!u)return;const b=await body(req),topicId=numericId(b.topicId);if(!b.prompt||!b.explanation||!Array.isArray(b.answer)||!topicId)return json(res,400,{error:'Заполните обязательные поля'});const x=await run('INSERT INTO questions(topic_id,type,prompt,explanation,difficulty,answer_json) VALUES(?,?,?,?,?,?)',topicId,b.type||'single',b.prompt,b.explanation,Math.min(3,Math.max(1,Number(b.difficulty)||1)),JSON.stringify(b.answer));for(const [i,label] of (b.options||[]).entries()) await run('INSERT INTO question_options(question_id,value,label,position) VALUES(?,?,?,?)',Number(x.lastInsertRowid),String(i),label,i);return json(res,201,{id:Number(x.lastInsertRowid)})}
  if(path.match(/^\/api\/admin\/questions\/\d+$/)&&req.method==='DELETE'){const u=await auth(req,res,true);if(u){const id=numericId(path.split('/').pop());if(!id)return json(res,400,{error:'Некорректный идентификатор задания'});await run('DELETE FROM questions WHERE id=?',id);return json(res,200,{ok:true})}}
  if(!res.headersSent)json(res,404,{error:'Маршрут не найден',code:'ROUTE_NOT_FOUND'});
 }catch(e){const status=e.status||500,code=e.code&&typeof e.code==='string'&&!/^\d+$/.test(e.code)?e.code:'INTERNAL_ERROR';console.error(JSON.stringify({route:`${req.method} ${path}`,code,postgresCode:e.code||null,message:e.message,stack:e.stack}));if(!res.headersSent)json(res,status,{error:status===500?'Внутренняя ошибка сервера':e.message,code})}
}
async function login(res,userId){const token=randomBytes(32).toString('hex');await run("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)",token,userId,new Date(Date.now()+2592000000).toISOString());res.setHeader('set-cookie',`session=${token}; Path=/; Max-Age=2592000; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);json(res,200,{ok:true});}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'};
async function start() {
 await migrate();
 return http.createServer((req,res)=>{const path=new URL(req.url,'http://x').pathname;if(path.startsWith('/api/'))return api(req,res,path);let file=normalize(join(PUBLIC,path==='/'?'index.html':path));if(!file.startsWith(PUBLIC)||!existsSync(file))file=join(PUBLIC,'index.html');res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(readFileSync(file));}).listen(PORT,()=>console.log(`EGE Platform: http://localhost:${PORT}`));
}
if (require.main === module) start().catch(error=>{console.error(error);process.exit(1)});
module.exports={start,api};
