const http = require('node:http');
const { readFileSync, existsSync } = require('node:fs');
const { extname, join, normalize } = require('node:path');
const { randomBytes, scryptSync, timingSafeEqual } = require('node:crypto');
const { migrate, rows, row, run } = require('./src/db');
migrate();

const PORT=Number(process.env.PORT||3000), PUBLIC=join(__dirname,'public');
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
const body=async req=>{let data='';for await(const chunk of req){data+=chunk;if(data.length>1e6)throw Error('Слишком большой запрос');}try{return JSON.parse(data||'{}')}catch{throw Error('Некорректный JSON')}};
const hash=p=>{const s=randomBytes(16).toString('hex');return `${s}:${scryptSync(p,s,64).toString('hex')}`};
const verify=(p,h)=>{const [s,v]=h.split(':');const a=Buffer.from(v,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)};
function userFor(req){const token=(req.headers.cookie||'').match(/(?:^|; )session=([^;]+)/)?.[1];if(!token)return null;return row("SELECT u.id,u.name,u.email,u.role,u.xp FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now')",token)||null;}
function auth(req,res,admin=false){const u=userFor(req);if(!u){json(res,401,{error:'Войдите в аккаунт'});return null}if(admin&&u.role!=='admin'){json(res,403,{error:'Недостаточно прав'});return null}return u;}
const safeUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,xp:u.xp,level:Math.floor(u.xp/500)+1});
function stats(uid){
 const total=row('SELECT COUNT(*) n, COALESCE(ROUND(AVG(correct)*100),0) accuracy FROM attempts WHERE user_id=?',uid);
 const activity=rows("SELECT day,solved FROM activity_days WHERE user_id=? ORDER BY day DESC LIMIT 30",uid);
 let streak=0,d=new Date(); const set=new Set(activity.map(a=>a.day)); while(set.has(d.toISOString().slice(0,10))){streak++;d.setUTCDate(d.getUTCDate()-1)}
 const progress=rows(`WITH RECURSIVE tree(root,id) AS (SELECT id,id FROM topics WHERE parent_id IS NULL UNION ALL SELECT tree.root,t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT root.id,root.slug,root.title,COALESCE(ROUND(AVG(tp.mastery)),0) mastery,COUNT(DISTINCT q.id) questions FROM topics root JOIN tree ON tree.root=root.id LEFT JOIN topic_progress tp ON tp.topic_id=tree.id AND tp.user_id=? LEFT JOIN questions q ON q.topic_id=tree.id WHERE root.parent_id IS NULL GROUP BY root.id ORDER BY root.position`,uid);
 const recent=rows(`SELECT a.correct,a.created_at,q.prompt,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 5`,uid);
 return {solved:total.n,accuracy:total.accuracy,streak,activity,progress,recent,mastery:Math.round(progress.reduce((s,p)=>s+p.mastery,0)/(progress.length||1))};
}
async function api(req,res,path){
 try{
  if(path==='/api/register'&&req.method==='POST'){const b=await body(req);if(!b.name?.trim()||!/^[^@]+@[^@]+\.[^@]+$/.test(b.email||'')||(b.password||'').length<8)return json(res,400,{error:'Укажите имя, корректную почту и пароль от 8 символов'});try{const x=run('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)',b.name.trim(),b.email.toLowerCase(),hash(b.password));return login(res,Number(x.lastInsertRowid));}catch{return json(res,409,{error:'Эта почта уже зарегистрирована'})}}
  if(path==='/api/login'&&req.method==='POST'){const b=await body(req),u=row('SELECT * FROM users WHERE email=?',(b.email||'').toLowerCase());if(!u||!verify(b.password||'',u.password_hash))return json(res,401,{error:'Неверная почта или пароль'});return login(res,u.id)}
  if(path==='/api/logout'&&req.method==='POST'){const token=(req.headers.cookie||'').match(/session=([^;]+)/)?.[1];if(token)run('DELETE FROM sessions WHERE token=?',token);res.setHeader('set-cookie','session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax');return json(res,200,{ok:true})}
  if(path==='/api/me'){const u=auth(req,res);if(u)return json(res,200,{user:safeUser(u),stats:stats(u.id),examDate:process.env.EXAM_DATE||'2027-06-05'})}
  if(path==='/api/subjects'){const u=auth(req,res);if(u)return json(res,200,{subjects:rows('SELECT * FROM subjects ORDER BY id')})}
  if(path==='/api/topics'){const u=auth(req,res);if(!u)return;return json(res,200,{topics:rows(`WITH RECURSIVE descendants(root,id) AS (SELECT id,id FROM topics UNION ALL SELECT descendants.root,t.id FROM topics t JOIN descendants ON t.parent_id=descendants.id) SELECT t.*,COALESCE(ROUND(AVG(tp.mastery)),0) mastery,COUNT(DISTINCT q.id) question_count FROM topics t JOIN descendants d ON d.root=t.id LEFT JOIN topic_progress tp ON tp.topic_id=d.id AND tp.user_id=? LEFT JOIN questions q ON q.topic_id=d.id WHERE t.published=1 GROUP BY t.id ORDER BY t.position,t.id`,u.id)})}
  if(path.match(/^\/api\/topics\/\d+$/)){const u=auth(req,res);if(!u)return;const id=Number(path.split('/').pop()),topic=row(`SELECT t.*,s.title subject,COALESCE(tp.mastery,0) mastery FROM topics t JOIN subjects s ON s.id=t.subject_id LEFT JOIN topic_progress tp ON tp.topic_id=t.id AND tp.user_id=? WHERE t.id=? AND t.published=1`,u.id,id);if(!topic)return json(res,404,{error:'Тема не найдена'});const stat=row(`WITH RECURSIVE tree(id) AS (SELECT ? UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT COUNT(*) attempted,COALESCE(SUM(correct),0) correct FROM attempts a JOIN questions q ON q.id=a.question_id WHERE a.user_id=? AND q.topic_id IN tree`,id,u.id);return json(res,200,{topic,children:rows('SELECT * FROM topics WHERE parent_id=? AND published=1 ORDER BY position',id),stat})}
  if(path==='/api/attempts'){const u=auth(req,res);if(!u)return;const url=new URL(req.url,'http://x'),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||30));return json(res,200,{attempts:rows('SELECT a.id,a.answer_json,a.correct,a.duration_seconds,a.created_at,a.next_review_at,a.interval_days,a.review_stage,a.result_json,q.prompt,q.type,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT ?',u.id,limit)})}
  if(path.match(/^\/api\/training\/result\/\d+$/)){const u=auth(req,res);if(!u)return;const id=Number(path.split('/').pop()),result=row('SELECT a.id,a.answer_json,a.correct,a.duration_seconds,a.created_at,a.next_review_at,a.interval_days,a.review_stage,a.result_json,q.prompt,q.explanation,q.answer_json expected_json,t.title topic FROM attempts a JOIN questions q ON q.id=a.question_id JOIN topics t ON t.id=q.topic_id WHERE a.id=? AND a.user_id=?',id,u.id);return result?json(res,200,{result}):json(res,404,{error:'Результат не найден'})}
  if(path==='/api/training/next'){const u=auth(req,res);if(!u)return;const url=new URL(req.url,'http://x'),topic=Number(url.searchParams.get('topic'));let q=row(`WITH RECURSIVE tree(id) AS (SELECT ? UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id), last_attempt AS (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY question_id ORDER BY id DESC) rn FROM attempts a WHERE user_id=?) SELECT q.* FROM questions q LEFT JOIN last_attempt a ON a.question_id=q.id AND a.rn=1 WHERE q.active=1 AND (?=0 OR q.topic_id IN tree) AND (a.id IS NULL OR a.next_review_at<=datetime('now')) ORDER BY CASE WHEN a.id IS NULL THEN 0 ELSE 1 END,a.next_review_at,q.difficulty,RANDOM() LIMIT 1`,topic,u.id,topic);if(!q)q=row(`WITH RECURSIVE tree(id) AS (SELECT ? UNION ALL SELECT t.id FROM topics t JOIN tree ON t.parent_id=tree.id) SELECT q.* FROM questions q WHERE q.active=1 AND (?=0 OR q.topic_id IN tree) ORDER BY RANDOM() LIMIT 1`,topic,topic);if(!q)return json(res,404,{error:'Для этой темы пока нет заданий'});delete q.answer_json;return json(res,200,{question:q,options:rows('SELECT value,label FROM question_options WHERE question_id=? ORDER BY position',q.id)})}
  if(path==='/api/training/answer'&&req.method==='POST'){
   const u=auth(req,res);if(!u)return;const b=await body(req),q=row('SELECT * FROM questions WHERE id=? AND active=1',Number(b.questionId));if(!q)return json(res,404,{error:'Задание не найдено'});
   const expected=JSON.parse(q.answer_json),given=Array.isArray(b.answer)?b.answer.map(String):[String(b.answer??'')],norm=a=>a.map(x=>x.trim().toLowerCase());
   const correct=q.type==='sequence'?JSON.stringify(norm(given))===JSON.stringify(norm(expected)):norm(given).sort().join('|')===norm(expected).sort().join('|');
   const previous=row('SELECT review_stage FROM attempts WHERE user_id=? AND question_id=? ORDER BY id DESC LIMIT 1',u.id,q.id),stage=correct?Math.min(5,(previous?.review_stage||0)+1):0,interval=[1,2,4,7,14,30][stage];
   const xp=correct?20:5,result={correct,expected,explanation:q.explanation,xp};
   const attempt=run("INSERT INTO attempts(user_id,question_id,answer_json,correct,duration_seconds,next_review_at,interval_days,review_stage,result_json) VALUES(?,?,?,?,?,datetime('now',?),?,?,?)",u.id,q.id,JSON.stringify(given),correct?1:0,Math.max(0,Number(b.duration)||0),`+${interval} days`,interval,stage,JSON.stringify(result));
   run("INSERT INTO activity_days(user_id,day,solved) VALUES(?,date('now'),1) ON CONFLICT(user_id,day) DO UPDATE SET solved=solved+1",u.id);run('UPDATE users SET xp=xp+? WHERE id=?',xp,u.id);
   const topicStats=row('SELECT COUNT(*) n,AVG(correct)*100 score FROM attempts a JOIN questions q ON q.id=a.question_id WHERE a.user_id=? AND q.topic_id=?',u.id,q.topic_id),mastery=Math.min(100,Math.round(topicStats.score*Math.min(1,topicStats.n/5)));
   run("INSERT INTO topic_progress(user_id,topic_id,mastery) VALUES(?,?,?) ON CONFLICT(user_id,topic_id) DO UPDATE SET mastery=excluded.mastery,updated_at=CURRENT_TIMESTAMP",u.id,q.topic_id,mastery);
   return json(res,200,{...result,attemptId:Number(attempt.lastInsertRowid),nextReviewInDays:interval,stats:stats(u.id)});
  }
  if(path==='/api/admin/stats'){const u=auth(req,res,true);if(u)return json(res,200,{users:rows(`SELECT u.id,u.name,u.email,u.xp,COUNT(a.id) solved,COALESCE(ROUND(AVG(a.correct)*100),0) accuracy FROM users u LEFT JOIN attempts a ON a.user_id=u.id WHERE u.role='student' GROUP BY u.id ORDER BY solved DESC`),counts:row('SELECT (SELECT COUNT(*) FROM users WHERE role="student") students,(SELECT COUNT(*) FROM questions) questions,(SELECT COUNT(*) FROM attempts) attempts')})}
  if(path==='/api/admin/questions'&&req.method==='GET'){const u=auth(req,res,true);if(u)return json(res,200,{questions:rows('SELECT q.id,q.prompt,q.type,q.difficulty,q.active,t.title topic FROM questions q JOIN topics t ON t.id=q.topic_id ORDER BY q.id DESC')})}
  if(path==='/api/admin/questions'&&req.method==='POST'){const u=auth(req,res,true);if(!u)return;const b=await body(req);if(!b.prompt||!b.explanation||!Array.isArray(b.answer)||!b.topicId)return json(res,400,{error:'Заполните обязательные поля'});const x=run('INSERT INTO questions(topic_id,type,prompt,explanation,difficulty,answer_json) VALUES(?,?,?,?,?,?)',b.topicId,b.type||'single',b.prompt,b.explanation,Math.min(3,Math.max(1,Number(b.difficulty)||1)),JSON.stringify(b.answer));(b.options||[]).forEach((label,i)=>run('INSERT INTO question_options(question_id,value,label,position) VALUES(?,?,?,?)',Number(x.lastInsertRowid),String(i),label,i));return json(res,201,{id:Number(x.lastInsertRowid)})}
  if(path.match(/^\/api\/admin\/questions\/\d+$/)&&req.method==='DELETE'){const u=auth(req,res,true);if(u){run('DELETE FROM questions WHERE id=?',Number(path.split('/').pop()));return json(res,200,{ok:true})}}
  json(res,404,{error:'Маршрут не найден'});
 }catch(e){console.error(e);json(res,500,{error:'Внутренняя ошибка сервера'})}
}
function login(res,userId){const token=randomBytes(32).toString('hex');run("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))",token,userId);res.setHeader('set-cookie',`session=${token}; Path=/; Max-Age=2592000; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`);json(res,200,{ok:true});}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
http.createServer((req,res)=>{const path=new URL(req.url,'http://x').pathname;if(path.startsWith('/api/'))return api(req,res,path);let file=normalize(join(PUBLIC,path==='/'?'index.html':path));if(!file.startsWith(PUBLIC)||!existsSync(file))file=join(PUBLIC,'index.html');res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(readFileSync(file));}).listen(PORT,()=>console.log(`EGE Platform: http://localhost:${PORT}`));
