CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'student' CHECK(role IN ('student','admin')),
  xp INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', icon TEXT NOT NULL DEFAULT 'dna');
CREATE TABLE IF NOT EXISTS topics (
  id INTEGER PRIMARY KEY, subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES topics(id) ON DELETE CASCADE, slug TEXT NOT NULL, title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '', theory TEXT NOT NULL DEFAULT '', position INTEGER NOT NULL DEFAULT 0,
  UNIQUE(subject_id, slug)
);
CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY, topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK(type IN ('single','multiple','matching','sequence','text')),
  prompt TEXT NOT NULL, explanation TEXT NOT NULL, difficulty INTEGER NOT NULL DEFAULT 1 CHECK(difficulty BETWEEN 1 AND 3),
  answer_json TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS question_options (id INTEGER PRIMARY KEY, question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE, value TEXT NOT NULL, label TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS attempts (
  id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE, answer_json TEXT NOT NULL,
  correct INTEGER NOT NULL, duration_seconds INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  next_review_at TEXT, interval_days INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS topic_progress (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE, mastery INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,topic_id));
CREATE TABLE IF NOT EXISTS activity_days (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, day TEXT NOT NULL, solved INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(user_id,day));
CREATE TABLE IF NOT EXISTS mock_exams (id INTEGER PRIMARY KEY, subject_id INTEGER NOT NULL REFERENCES subjects(id), title TEXT NOT NULL, duration_minutes INTEGER NOT NULL DEFAULT 210, published INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS mock_exam_questions (mock_exam_id INTEGER NOT NULL REFERENCES mock_exams(id) ON DELETE CASCADE, question_id INTEGER NOT NULL REFERENCES questions(id), position INTEGER NOT NULL, PRIMARY KEY(mock_exam_id,question_id));
CREATE TABLE IF NOT EXISTS mock_exam_attempts (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), mock_exam_id INTEGER NOT NULL REFERENCES mock_exams(id), started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at TEXT, score INTEGER, answers_json TEXT NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS idx_attempts_user_question ON attempts(user_id,question_id);
CREATE INDEX IF NOT EXISTS idx_questions_topic ON questions(topic_id,active);
